#------------------------------------------------------------------------------
# General
#------------------------------------------------------------------------------
name: "GRATHWOHL.ME"
description: "A place for my radical immersions."
language: "en"

url: http://127.0.0.1:4000
baseurl: ''

#------------------------------------------------------------------------------
# Markdown processor and code highlighting
#------------------------------------------------------------------------------
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

#------------------------------------------------------------------------------
# Pagination and friendly URLs
#------------------------------------------------------------------------------
paginate: 3
paginate_path: /page-:num
permalink: /:title

#------------------------------------------------------------------------------
# Social sharing, comments and RSS.
#------------------------------------------------------------------------------

enable-share: true
twitter: AndrewUnmuted
github: agrathwohl

rss-feed-limit: 20
rss-show-full: false

#------------------------------------------------------------------------------
# Configuration, plugins, gems, etc..
#------------------------------------------------------------------------------
source: .
destination: ./_site
gems: ['jekyll-paginate']

sass:
    style: :compressed
    sass_dir: assets/css/
